let PRODUCTS={glow:{id:'glow',name:'Glow Body Cream',size:'500ml',price:65,img:'./assets/glow-body-cream.jpeg',description:'Rich body cream for deep nourishment, softness and a healthy-looking glow.',active:true},lotion50:{id:'lotion50',name:'Sheara Lotion',size:'50ml',price:15,img:'./assets/lotion-50ml.jpeg',description:'Lightweight moisture for soft, radiant-looking skin, enriched with niacinamide, sunflower oil and vitamin E.',active:true},lotion100:{id:'lotion100',name:'Sheara Lotion',size:'100ml',price:25,img:'./assets/lotion-100ml.jpeg',description:'Our everyday lotion in a larger size, enriched with niacinamide, sunflower oil and vitamin E.',active:true}};
let cart=JSON.parse(localStorage.getItem('sheara_cart')||'[]');
const money=n=>'GHS '+Number(n).toFixed(2).replace('.00','');
async function loadProducts(){try{const r=await fetch('./api/products');if(!r.ok)throw new Error('API unavailable');const d=await r.json();PRODUCTS=Object.fromEntries((d.products||[]).map(p=>[p.id,p]));}catch(e){console.warn('Using local product preview');}renderProductGrids();renderCart()}
function save(){localStorage.setItem('sheara_cart',JSON.stringify(cart))}
function add(id){if(!PRODUCTS[id])return;const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});save();renderCart();openCart()}
function changeQty(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.id!==id);save();renderCart()}
function removeItem(id){cart=cart.filter(i=>i.id!==id);save();renderCart()}
function renderCart(){const count=cart.reduce((s,i)=>s+i.qty,0);document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=count);const el=document.getElementById('drawer-items');if(!el)return;if(!cart.length){el.innerHTML='<div class="empty">Your bag is empty.<br><br><a href="./shop.html">Shop Sheara</a></div>'}else{el.innerHTML=cart.map(i=>{const p=PRODUCTS[i.id];if(!p)return '';return `<div class="cart-item"><img src="${p.image_data||p.img}" alt="${p.name}"><div><h4>${p.name}</h4><div class="muted">${p.size} · ${money(p.price)}</div><div class="qty"><button onclick="changeQty('${i.id}',-1)">−</button><span>${i.qty}</span><button onclick="changeQty('${i.id}',1)">+</button></div></div><button class="remove" onclick="removeItem('${i.id}')">Remove</button></div>`}).join('')}
const total=cart.reduce((s,i)=>s+(PRODUCTS[i.id]?Number(PRODUCTS[i.id].price)*i.qty:0),0);const totalEl=document.getElementById('drawer-total');if(totalEl)totalEl.textContent=money(total)}
function productCard(p){return `<article class="product-card"><a class="product-image" href="./product.html?id=${encodeURIComponent(p.id)}"><img src="${p.image_data||p.img}" alt="${p.name} ${p.size}"></a><div class="product-info"><div class="meta"><h3>${p.name}</h3><span class="price">${money(p.price)}</span></div><div class="size">${p.size}</div><p>${p.description||''}</p><div class="actions"><button class="smallbtn primary" data-add="${p.id}">Add to bag</button><a class="smallbtn light" href="./product.html?id=${encodeURIComponent(p.id)}">View</a></div></div></article>`}
function renderProductGrids(){document.querySelectorAll('[data-product-grid]').forEach(grid=>{grid.innerHTML=Object.values(PRODUCTS).map(productCard).join('');grid.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>add(b.dataset.add)))})}
function openCart(){document.getElementById('drawer')?.classList.add('open');document.getElementById('overlay')?.classList.add('show')}
function closeCart(){document.getElementById('drawer')?.classList.remove('open');document.getElementById('overlay')?.classList.remove('show')}
function init(){document.getElementById('bag')?.addEventListener('click',openCart);document.getElementById('close-cart')?.addEventListener('click',closeCart);document.getElementById('overlay')?.addEventListener('click',closeCart);document.getElementById('hamb')?.addEventListener('click',()=>document.getElementById('mobile-nav')?.classList.toggle('open'));loadProducts()}
document.addEventListener('DOMContentLoaded',init);
